# Site settings
title: AutoMerge
email: your-email@domain.com
description: >
  Conflict resolution for structured merge.

baseurl: "/automerge" # the subpath of your site, e.g. /blog/
url: https://thufv.github.io/automerge # the base hostname & protocol for your site
git_address: https://github.com/thufv/automerge
git_edit_address: https://github.com/thufv/automerge/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: flatly

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _install
    type: install
  values:
    layout: install
    sectionid: install
    seo:
      type: "WebPage"

- scope:
    path: _artifact
    type: artifact
  values:
    layout: artifact
    sectionid: artifact
    seo:
      type: "WebPage"

collections:
  install:
    permalink: /:collection/:path/
    output: true
  artifact:
    permalink: /:collection/:path/
    output: true